apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-kvxk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0047-tenant/ci10t-786-0047-app/devfile-sample-kvxk@sha256:983aa770ea666af48dda50956d4fd05e013326e58a303c71679bfc4c63419607
        name: my-nodejs
        resources: {}
status: {}
