apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-kvxk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-kvxk
    app.kubernetes.io/part-of: ci10t-786-0047-app
  name: devfile-sample-kvxk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-kvxk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-kvxk
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0047-tenant/ci10t-786-0047-app/devfile-sample-kvxk@sha256:983aa770ea666af48dda50956d4fd05e013326e58a303c71679bfc4c63419607
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
